schemas:
  - table: users
    columns:
      - id
      - firstname
      - lastname
      - email
      - age
    encrypted:
      - column: firstname
      - column: lastname
      - column: email
        token_type: email
        tokenized: true
      - column: age
        token_type: int32
        tokenized: true