schemas:
  - table: customers
    columns:
      - customer_id
      - first_name
      - last_name
      - email
      - phone
      - address
    encrypted:
      - column: first_name
      - column: last_name
      - column: email
        token_type: email
        tokenized: true
      - column: phone
      - column: address
